services:
  some-mysql:
    image: mysql:8.0.31-oracle
    depends_on:
      - selenium
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: testpwd
    networks:
      - scrapenet
    volumes:
      - /root/mysqlvol:/var/lib/mysql

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: 2gb
    networks:
      - scrapenet
      
  scrape_app:
    build: .
    depends_on: 
      - some-mysql
    networks:
      - scrapenet
    environment:
      PYTHONUNBUFFERED: 0

networks:
  scrapenet: {}